name: deploy

on:
  push:
    branches:
      - main # Production
      - staging # Pré-production
      - 'release/**' # Pattern : release/v1.0, release/v2.0, ...

permissions:
  contents: read

jobs: 
  deploy: 
    name: Deploy to ${{ github.ref }}
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code 
        uses: actions/checkout@v6.0.1

      - name: Afficher la branch
        run: |
          echo "Déploiement sur la branche : ${{ github.ref_name }}"
          echo "Event : ${{ github.event_name}}"

